### ISSUE TITLE
ABAC Policy

### ISSUE THREAD

**Issue by pietrotedeschi** [simplicii/spring-abac-sample#1]
Can you describe how (or if) the user can make a policy using boolean operators like AND and OR (using JsonImpl or JdbcImpl)?

**Comment by simplicii** [comment]
Hi,
The Pull request for ABAC to be part of spring security was closed after a little discussion.
Result:
For now users should use SpEL, as Spring-ABAC basel on spring-acl and this does not scale for large data.
At least not the @PostFilter and @PostAuthorize

This is the reason I stopped maintaining the spring-abac.

**Comment by simplicii** [comment]
To answer your question, yes as @Preauthorize and co are able to interpret SpEL.

This will give a 403 on the same example:

```
 @RequestMapping(path = "sec")
    @PreAuthorize("checkPolicy('EDIT') && false")
    public String sec(){
        return "sec ok";
    }
```

**Comment by anhtv08** [comment]
Hi simplicii,  thanks for implementing of abac security model.

I am looking for this kind of implementation for your project. Can you share the sourcecode of spring-abac module so we can fork from there and do some customization for our current project

**Comment by simplicii** [comment]
Hi,
my pull request was denied because I depend on Springs @PostFilter which is implemented very unperformant. 
I started reimplement @PostFilter to inject the Filter criteria (here ABAC) direct in the select query. So we have a much more efficient select. (retrieving the data from db and then deny access afterward is very inefficient)
Unfortunately I have no time to complete it.
I would recomment that you check the code from PostFilter and implement your own version of it by injecting the "filter" as a join if you need to be performant.
I added you as contributer.
greets
Renato
